apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: infrastructure
spec:
  releaseName: sealed-secrets-controller
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: sealed-secrets
    version: 1.10.3
